### ISSUE TITLE
Error running the parser method on scala 2.11

### ISSUE THREAD

**Issue by chmandrade** [acrisci/commander-scala#3]
Error running the parser method on scala 2.11

I am using the package: "com.github.acrisci" % "commander_2.11" % "0.1.0" withSources()

Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;
        at com.github.acrisci.commander.Program.normalize(Program.scala:314)
        at com.github.acrisci.commander.Program.parse(Program.scala:225)
        at com.databricks.apps.twitterClassifier.CollectOptions$.parse(CollectOptions.scala:21)
        at com.databricks.apps.twitterClassifier.Collect$.delayedEndpoint$com$databricks$apps$twitterClassifier$Collect$1(Collect.scala:11)
        at com.databricks.apps.twitterClassifier.Collect$delayedInit$body.apply(Collect.scala:10)

**Comment by acrisci** [comment]
I think this error can happen when you try to run your project with a newer version of scala. Are you sure you are running the project with scala 2.11?

**Comment by SuperHippo001** [comment]
Any update for this issue? Thanks!
